### ISSUE TITLE
Freeworld codecs not available

### ISSUE THREAD

**Issue by gkeep** [ungoogled-software/ungoogled-chromium-fedora#13]
Please provide a package with freeworld codecs enabled. The flatpak build includes them, as does the `chromium-browser-privacy` package in [RPM Fusion](https://rpmfusion.ip-connect.info/free/fedora/releases/34/Everything/source/SRPMS/repoview/chromium-browser-privacy.html).  

Said `chromium-browser-privacy` package is very outdated, last update being at 2021-02-06.

**Comment by wchen342** [comment]
Freeworld cannot be built on OBS, you will have to build yourself by using chromium source from https://commondatastorage.googleapis.com/chromium-browser-official/chromium-%%{version}.tar.xz and `%global freeworld 1`.

I have never tried building the freeworld version so there may be bugs in `spec` file, so please report back if you find any and PRs are welcomed.

**Comment by gkeep** [comment]
> Freeworld cannot be built on OBS

Real shame, compiling is not an option for me at the moment. Any chance you can update the `chromium-browser-privacy`  package in RPM Fusion or ping its maintainer?

**Comment by wchen342** [comment]
I think the repo is https://github.com/rpmfusion/chromium-browser-privacy, it seems they updated the repo recently but I cannot find the actual package on RPMFusion (probably because @qvint is the only one who can write to the RPMFusion package, and he hasn't shown up for some time).

**Comment by wchen342** [comment]
I may be able to build a freeworld version with my build server for Android version. But it will take some time to set up the whole Github Actions stuff, etc.
