### ISSUE TITLE
Ungoogled-Chromium not working in Fedora 35

### ISSUE THREAD

**Issue by finxol** [ungoogled-software/ungoogled-chromium-fedora#18]
Ungoogled-Chromium worked perfectly on Fedora 34, but after updating to Fedora 35 nothing in ungoogled-chromium works anymore.. 

According to DNF, I'm using version 94 :
```bash
chromium.x86_64                                                                          94.0.4606.81-1.fc35                                              updates
chromium-browser-privacy.x86_64                                                          88.0.4324.150-1.fc34                                             @rpmfusion-free
```

When I start chromium-browser-privacy, I cannot load any page, not even local Chromium pages. I only get the "Chrashed. Can't open this page" message, with "Error Code: 159".
The 8 different extensions don't load ether. I only get "[extension name] has crashed. Click to reload extension", which doesn't change anything.

**Comment by wchen342** [comment]
Are you using `chromium-browser-privacy` or `ungoogled-chromium`? They are two different packages, the former is not maintained by me.

**Comment by finxol** [comment]
I am using chromium-browser-privacy.. Do you know where I should report this issue ?

**Comment by wchen342** [comment]
The RPMFusion package page is here: https://admin.rpmfusion.org/pkgdb/package/free/chromium-browser-privacy/ which has a bug report. There is a mirror on Github, but that one doesn't have an issue section.

**Comment by shadow7483147** [comment]
I was also on chromium-browser-privacy, so I switched to this repo in the meantime. Everything seems to work fine, user profiles being shared, which is nice.
Only exception is #20 but that's a separate concern.

**Comment by shadow7483147** [comment]
update.
https://twitter.com/rpmfusion_team/status/1458451173363621897?s=20
