### ISSUE TITLE
Building latest version 96 is not working

### ISSUE THREAD

**Issue by rkfox** [ungoogled-software/ungoogled-chromium-fedora#22]
Build was working fine with the previous 94 version. Now I can't get it to build.

```+ sed -i 's|arm-linux-gnueabihf-|arm-linux-gnu-|g' build/toolchain/linux/BUILD.gn
+ sed -i 's|exec "${THIS_DIR}/ninja-linux${LONG_BIT}"|exec "/usr/bin/ninja-build"|g' ../depot_tools/ninja
sed: can't read ../depot_tools/ninja: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.uWzfYL (%prep)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.uWzfYL (%prep)```

**Comment by rkfox** [comment]
I solved for my setup by reusing the old revision of depot-tools renamed to the new revision...

**Comment by wchen342** [comment]
That's strange, OBS runs fine so the `spec` file shall be correct. Can you check whether that file exists in depot_tools tarball (I suppose you download it directly)? Also check whether that file is included in `ungoogled-chromium`'s pruning list. Somethings file got pruned accidentally.

**Comment by rkfox** [comment]
I download depot_tools manually. Building from the spec file spits out a required revision of depot_tools. The previous revision is ~7.6mb and has `depot_tools/ninja` while the new required revision does not. The old revision still works as long as it is renamed to the new revision.

**Comment by wchen342** [comment]
I just checked locally again, the file indeed exists in the `depot_tools` folder for the revision in `spec` file. Maybe your download is corrupted or something else deleted the file?
