### ISSUE TITLE
Chromium 90

### ISSUE THREAD

**Issue by braewoods** [ungoogled-software/ungoogled-chromium-fedora#7]
@wchen342 It appears Chromium 90 has finally made it into the upstream Fedora sources. You want to work on the upgrade?

**Comment by wchen342** [comment]
Yeah I will work on that this weekend, but if you want to start now it's ok.

**Comment by braewoods** [comment]
I'm still ironing out Debian and friends.

**Comment by wchen342** [comment]
Ok, then I will work on this.

**Comment by wchen342** [comment]
Btw since F34 is released, F32 will soon reach EOL so it can be removed if it is more convenient.

**Comment by braewoods** [comment]
@wchen342 I noticed you pushed the build to the main repository first. Just FYI, if you want to upload the current master branch to OBS, you can use the manual activation trigger for the OBS Upload workflow. You can find it under the Actions tab. This is mainly for uploading test builds but it'll also upload to the production project if master currently rests on a tagged commit.

**Comment by braewoods** [comment]
@wchen342 Also, were you wanting me to add F34 to the repository lists?

**Comment by wchen342** [comment]
@braewoods I am curious how to use the script for testing before I push a tag? I am not sure what the envs should be, like `OBS_API_PROJECT`.

And yes, please enable Fedora 34, I am (and most people shall) be on it now. F32 will be in EOL this month so you can remove it.

**Comment by braewoods** [comment]
You should be able to run it from the GitHub UI in this repository. It's under Actions > OBS Upload > Run workflow > Run workflow.

**Comment by wchen342** [comment]
Yes I know that, but that will just upload to the main repo right? I wanted to test a commit in a testing repo first, rahter than upload to main repo every time. Or is that the way you do it with Debian?

Also, do you know why [https://software.opensuse.org//download.html?project=home%3Aungoogled_chromium&package=ungoogled-chromium-fedora](https://software.opensuse.org//download.html?project=home%3Aungoogled_chromium&package=ungoogled-chromium-fedora) is blank?

**Comment by wchen342** [comment]
Actually I am now more confused. The [`spec` file](https://build.opensuse.org/package/view_file/home:ungoogled_chromium/ungoogled-chromium-fedora/ungoogled-chromium.spec?expand=1) is got getting updated?

**Comment by braewoods** [comment]
If the file is exactly the same as the one that was there previously then it won't be updated.

**Comment by braewoods** [comment]
Also note the manual upload goes to the testing or production project depending on whether the current commit is part of a tag or not.

**Comment by braewoods** [comment]
So you need another commit to be on top to upload to the testing project. I'll see if I can work out a different way to determine where to upload to but I don't know if there's a way for the script to know which trigger activated it.

**Comment by braewoods** [comment]
Oh, and I can't do any maintenance on the repository lists for now because some yahoo decided to "link" to our package so I can't delete any.

**Comment by wchen342** [comment]
> If the file is exactly the same as the one that was there previously then it won't be updated.

But it's not the same. You can easily see the version number inside is different.

> the manual upload goes to the testing or production project depending on whether the current commit is part of a tag or not.

Ok I see. I think I can work with that.

**Comment by braewoods** [comment]
Did you push a tag at the same time you pushed the commit? The only explanation I can think of is the script was run on the wrong commit.

**Comment by braewoods** [comment]
A test build is now running on OBS testing project. As for why the repository instructions are blank; I don't know. It has been that way for awhile and is partly why I had to include our own instructions for installing the repository.

**Comment by wchen342** [comment]
So the script runs on the latest commit instead of the specific commit the Action is running on? Then you need to update the script to let it checkout the specific commit it is running on. Github Actions has an variable for that.

Also why is the missing checksum? That is a patch file.

**Comment by wchen342** [comment]
> I can't do any maintenance on the repository lists for now

That's a strange mechanism. Can you at least enable F34?

**Comment by braewoods** [comment]
@wchen342 Because the patch file is a complete URL instead of a local file I needed to add a checksum to validate it. Remember, you asked for this?

**Comment by braewoods** [comment]
Also, the repositories have been resolved already. You can ignore that comment now. I found out I had to force it through another way.

**Comment by wchen342** [comment]
> Because the patch file is a complete URL instead of a local file

Ok I must missed that link, because it is also among local files in the repo. I will push an update for this.

**Comment by braewoods** [comment]
Erm, no. The script runs on whatever commit the Action is running on. It only has two triggers now; either it'll trigger at the commit of a tag or the latest commit when you do a manual activation. I was just speculating as to why it wouldn't upload the right payload.

**Comment by braewoods** [comment]
I haven't witnessed that in the other repos so I can't really say why it occurred. But I don't push the commit I tend to tag in the same push (assuming that's even possible); I push the tags separately. So I thought maybe you were trying to do both at once which might create a strange situation.

**Comment by braewoods** [comment]
@wchen342 In that  case feel free to undo my change. I was just trying to make it do the least amount of work to make it build.

**Comment by wchen342** [comment]
No I didn't push the commit and the tag at the same time (I didn't know you can actually do that). Maybe wait until next update and see whether it works properly.

**Comment by braewoods** [comment]
Ok. I retagged the release so I'll see if it makes it through OBS build now.

**Comment by wchen342** [comment]
F34 arm64 doesn't have compliant worker it seems. On x64 I needed to lower memory to 24G, not sure about arm64. Maybe need to wait for them to update their building machine settings.

**Comment by braewoods** [comment]
Don't worry about arm64. I consider ARM to be a best effort port. Our priority is only x86 architectures due to their ubiquity. I can't really name many arm64 systems that regular people use anywway.

**Comment by wchen342** [comment]
Yeah then just leave it. I checked the files and they seems right this time, so it should work now.
