### ISSUE TITLE
Chromium 91

### ISSUE THREAD

**Issue by braewoods** [ungoogled-software/ungoogled-chromium-fedora#8]
Whenever it's ready.

**Comment by wchen342** [comment]
I am waiting for upstream updates.

**Comment by wchen342** [comment]
It seems OBS has no compliant workers for F34 on both x64 and arm64. Do you know what happened?

**Comment by braewoods** [comment]
I don't know. I didn't change anything. It may be a byproduct of trying to get them to fix the F34 issue.

**Comment by braewoods** [comment]
It seems to be resolved. Are you done with Chromium 91?

**Comment by wchen342** [comment]
CentOS 7 has a compile error but upstream is not updating patches so I cannot solve it now. Otherwise it's good.
