### ISSUE TITLE
aarch64 version

### ISSUE THREAD

**Issue by misshandel** [ungoogled-software/ungoogled-chromium-fedora#9]
On the OBS site it seems that the aarch64 build is failing and that there is no aarch64 for Fedora.

**Comment by wchen342** [comment]
The aarch64 version is enabled as a best effort port. The only guarantee is the patches will be following the upstream `chromium` package from Fedora.

**Comment by braewoods** [comment]
It's an issue with OBS and I don't know when it will be corrected. I left them a note about it.

**Comment by braewoods** [comment]
It appears to be resolved.
